server.port=15150

spring.datasource.url=jdbc:h2:file:./data/linkedin-content-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

ai.python.base-url=https://linkedin-generator-api.onrender.com
ai.python.generate-path=/api/ai/generate-linkedin-post
